coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0.05%
        base: auto
comment: false
ignore:
  - "evap/development/views.py"
  - "evap/development/urls.py"
