os: linux
language: python
python: "3.7"
dist: xenial
cache: pip

services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database evap;' -U postgres
install:
  - pip install -r requirements-travis.txt
  - echo 'SECRET_KEY = "evap-travis-secret-key"' >> evap/localsettings.py

jobs:
  include:
    - name: Lint Python
      script:
        - pylint evap -j 0
    - name: Test Backup Script
      script:
        - deployment/test_backup_and_restore_on_travis.sh
    - name: Test Python
      script:
        - coverage run manage.py test && codecov -X gcov
    - name: Test Python (debug mode)
      script:
        - python manage.py test --debug-mode
    - name: Test Python (backwards)
      script:
        - python manage.py test --reverse
    - name: Test Typescript
      services:
        - postgresql
        - redis
        - xvfb
      install:
        - pip install -r requirements-travis.txt
        - echo 'SECRET_KEY = "evap-travis-secret-key"' >> evap/localsettings.py
        - wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh --no-verbose --output-document - | bash
        - deployment/install_dart_sass.sh
        - . "${HOME}/.nvm/nvm.sh"
        - nvm install 15.4.0
        - yarn install
      script:
        - python manage.py scss
        - python manage.py ts compile
        - python manage.py ts generate_fixtures
        - python manage.py ts test
